package com.shashanksoni.kharchahogayabhai.ui.theme

import androidx.compose.ui.graphics.Color

// A green-leaning scheme: money in the app, not a generic baseline palette.
internal val GreenPrimaryLight = Color(0xFF196C4B)
internal val GreenOnPrimaryLight = Color(0xFFFFFFFF)
internal val GreenPrimaryContainerLight = Color(0xFFA6F2C7)
internal val GreenOnPrimaryContainerLight = Color(0xFF00210F)
internal val SecondaryLight = Color(0xFF4E6355)
internal val OnSecondaryLight = Color(0xFFFFFFFF)
internal val SecondaryContainerLight = Color(0xFFD0E8D7)
internal val OnSecondaryContainerLight = Color(0xFF0B1F14)
internal val TertiaryLight = Color(0xFF3B6470)
internal val OnTertiaryLight = Color(0xFFFFFFFF)
internal val TertiaryContainerLight = Color(0xFFBFE9F8)
internal val OnTertiaryContainerLight = Color(0xFF001F27)
internal val ErrorLight = Color(0xFFBA1A1A)
internal val OnErrorLight = Color(0xFFFFFFFF)
internal val ErrorContainerLight = Color(0xFFFFDAD6)
internal val OnErrorContainerLight = Color(0xFF410002)
internal val BackgroundLight = Color(0xFFFBFDF8)
internal val OnBackgroundLight = Color(0xFF191C1A)
internal val SurfaceVariantLight = Color(0xFFDCE5DC)
internal val OnSurfaceVariantLight = Color(0xFF414942)
internal val OutlineLight = Color(0xFF717972)
internal val OutlineVariantLight = Color(0xFFC0C9C0)
internal val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val SurfaceContainerLowLight = Color(0xFFF5F7F2)
internal val SurfaceContainerLight = Color(0xFFEFF2EC)
internal val SurfaceContainerHighLight = Color(0xFFE9ECE6)
internal val SurfaceContainerHighestLight = Color(0xFFE3E7E0)
internal val SurfaceDimLight = Color(0xFFDBDED7)

internal val GreenPrimaryDark = Color(0xFF8BD6AB)
internal val GreenOnPrimaryDark = Color(0xFF003920)
internal val GreenPrimaryContainerDark = Color(0xFF00522F)
internal val GreenOnPrimaryContainerDark = Color(0xFFA6F2C7)
internal val SecondaryDark = Color(0xFFB5CCBB)
internal val OnSecondaryDark = Color(0xFF213528)
internal val SecondaryContainerDark = Color(0xFF374B3E)
internal val OnSecondaryContainerDark = Color(0xFFD0E8D7)
internal val TertiaryDark = Color(0xFFA4CDDC)
internal val OnTertiaryDark = Color(0xFF053541)
internal val TertiaryContainerDark = Color(0xFF234C58)
internal val OnTertiaryContainerDark = Color(0xFFBFE9F8)
internal val ErrorDark = Color(0xFFFFB4AB)
internal val OnErrorDark = Color(0xFF690005)
internal val ErrorContainerDark = Color(0xFF93000A)
internal val OnErrorContainerDark = Color(0xFFFFDAD6)
internal val BackgroundDark = Color(0xFF101410)
internal val OnBackgroundDark = Color(0xFFE1E4DE)
internal val SurfaceVariantDark = Color(0xFF414942)
internal val OnSurfaceVariantDark = Color(0xFFC0C9C0)
internal val OutlineDark = Color(0xFF8B938B)
internal val OutlineVariantDark = Color(0xFF414942)
internal val SurfaceContainerLowestDark = Color(0xFF0B0F0B)
internal val SurfaceContainerLowDark = Color(0xFF191C18)
internal val SurfaceContainerDark = Color(0xFF1D211C)
internal val SurfaceContainerHighDark = Color(0xFF272B26)
internal val SurfaceContainerHighestDark = Color(0xFF323630)
internal val SurfaceBrightDark = Color(0xFF363A35)

// Money direction is semantic, so these stay fixed even under dynamic colour.
internal val IncomeLight = Color(0xFF1B7A45)
internal val IncomeDark = Color(0xFF7ADFA5)
internal val ExpenseLight = Color(0xFFB3261E)
internal val ExpenseDark = Color(0xFFFFB4AB)
